name: GitHub Actions Demo
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Bump version and push tag
      uses: actions/checkout@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DRY_RUN: true
    - run: echo "💡 The ${{ env.tag }} and ${{ env.new_tag }}"
