name: GitHub Actions Demo
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write 
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Ctag
      id: version
      uses: anothrNick/github-tag-action@1.36.0
      #run: echo "::set-output name=author::$(uses anothrNick/github-tag-action@1.36.0)"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        WITH_V: true
        DRY_RUN: true
    - name: Tag
      id: tag 
      run: echo "::set-output name=mix-test::$(git tag)\n"
    
    - run: echo "${{steps.tag.outputs.*}}"
#    - run: echo "${{join(steps.tag.outputs.*, '\n')}}"
     
#     - name: Maven Build
#       run: mvn clean install
  
#     - uses: actions/checkout@v2
#     - uses: actions/setup-java@v2
#       with:
#           java-version: '11'
#           distribution: 'adopt'
#     - name: Publish package
#       run: mvn deploy -Dversion=r203 -Dregistry=https://github.com/Nikhil-Kaware/Test_Devops.git
#       env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
